### ISSUE TITLE
Глобальний конфіг для Many-to-Many

### ISSUE THREAD

**Issue by Sensetivity** [voskobovich/yii2-linker-behavior#11]
Вітаю, чи є спосіб додати глобальний конфіг для використання ManyToManySmartUpdater для Many-to-Many зв'язків?
P.S. В доках відсутній приклад, як власне змінювати апдейтер.

```
'tags_ids' => 'tags',
// на
'tags_ids' => [
                        'tags',
                        'updater' => [
                            'class' => ManyToManySmartUpdater::className(),
                        ],
                    ],
```

**Comment by ZAYEC77** [comment]
@Sensetivity підкажіть, а навіщо вам глобальний конфіг?

**Comment by voskobovich** [comment]
@Sensetivity глобально настраиваю класс апдейтера нет смысла. Лучше всегда это делать ясно и по месту.

За пробел в документации спасибо.
