### ISSUE TITLE
Некорректное создание AssociativeRowCondition в ManyToManySmartUpdater

### ISSUE THREAD

**Issue by ptz-nerf** [voskobovich/yii2-linker-behavior#12]
https://github.com/voskobovich/yii2-linker-behavior/blob/4.0.2-rc/src/updaters/ManyToManySmartUpdater.php#L117
На выходе всегда AssociativeRowCondition с isNewRecord = true и пустым значением.
Надо либо передать все в первом параметре, либо сделать что-то с конструктором(т.к. сейчас идет в него, но там ключи - позиции в конструкторе). Например:
```php
$rowCondition = Yii::createObject([
    'class' => $this->rowConditionClass,
    'isNewRecord' => false,
    'oldValue' => $currentRow[$viaTableColumnName],
]);
```

ПС: Сделать реквест сейчас нет возможности.

**Comment by voskobovich** [comment]
@ptz-nerf расскажи в чем заключается проблема?

**Comment by ptz-nerf** [comment]
@voskobovich $rowCondition создается некорректно: данные в Yii::createObject() передаются верные, но формат вызова некорректный, поэтому нельзя понять создается ли объект или обновляется старый: isNewRecord всегда true, oldValue == null.

**Comment by voskobovich** [comment]
@ptz-nerf я исправил. Есть возможность проверить?
Изменения лежат в ветке master.

**Comment by ptz-nerf** [comment]
@voskobovich, спасибо! Посмотрел изменения, все должно быть хорошо, в таком же виде на боевом проекте все работает. Можно закрывать. На выходных, возможно, проверю.

**Comment by vsivsivsi** [comment]
Установил расширение через композер "voskobovich/yii2-linker-behavior": "^4.0"
Целый день ловил и пытался исправить эту проблему, пока нашел this issue.
Подскажите, как можно установить через композер самую последнюю версию (с исправлениями).
Релиз, я так понимаю, не скоро..
Спасибо.

**Comment by ptz-nerf** [comment]
@vsivsivsi 
`composer require voskobovich/yii2-linker-behavior:dev-master`
