### ISSUE TITLE
Дополнительные поля в связующей таблице

### ISSUE THREAD

**Issue by sdelfi** [voskobovich/yii2-linker-behavior#16]
Вопрос по функционалу.

Есть связующая таблица для many-to-many. В этой таблице есть еще пара полей, в которые нужно заносить информацию. Есть ли такой функционал в данном behavior, либо обрабатывать отдельно?

Спасибо

**Comment by voskobovich** [comment]
@sdelfi есть, https://github.com/voskobovich/yii2-linker-behavior#custom-junction-table-values
