### ISSUE TITLE
Illegal string offset 'updater'

### ISSUE THREAD

**Issue by loveorigami** [voskobovich/yii2-linker-behavior#2]
После замены ManyToMany на Linker behavior при сохранении модели появляется ошибка
Illegal string offset 'updater'

![0001](https://cloud.githubusercontent.com/assets/98164/20865478/cede5658-ba24-11e6-98bc-1b41cce5e26a.jpg)

**Comment by voskobovich** [comment]
Сек, сейчас исправлю.

**Comment by loveorigami** [comment]
у меня перед 122 строкой print_r выдает 
$params string(4) "tabs"

**Comment by voskobovich** [comment]
@loveorigami покажи как у тебя сконфигурировано поведение в модели.

**Comment by loveorigami** [comment]
как в доке
```php
    return [
        [
            'class' => \voskobovich\linker\LinkerBehavior::className(),
            'relations' => [
            'relations' => [
                'tab_ids' => 'tabs', // getTabs()
                'group_ids' => 'groups', // getGroups()
                'service_ids' => 'services', // getServices()
            ],
        ],
    ];
```

**Comment by voskobovich** [comment]
```
            'relations' => [
            'relations' => [
```
это меня смущает. Ты скопировал код из проекта или накидал сам?

**Comment by loveorigami** [comment]
т.е. ошибка появляется верно. Ты ждешь массив, а туда передается строка

**Comment by loveorigami** [comment]
поправил выше.

**Comment by loveorigami** [comment]
вот тут 
```php
                // Many-to-many
                if (empty($params['updater']['class'])) {
                    $params['updater']['class'] = ManyToManyUpdater::className();
                }
```
на самом деле строка $params = tabs

**Comment by voskobovich** [comment]
Да, я уже увидел. Эта ситуация не обыграна в тестах. Сейчас исправлю :)

**Comment by voskobovich** [comment]
@loveorigami отправил изменения, залей себе @dev ревизию.

**Comment by loveorigami** [comment]
Обновился. Потестил. заработало!
Спасибо.

**Comment by voskobovich** [comment]
Ок. Сейчас выпущу RC

**Comment by voskobovich** [comment]
Готово!
Тестируй дальше, я постараюсь реагировать оперативно.
Над тестами еще работаю, так что пиши :)
