### ISSUE TITLE
Travis CI for PR not working

### ISSUE THREAD

**Issue by sergiobelya** [voskobovich/yii2-linker-behavior#21]
CI errors:
1)
Downloading archive: https://s3.amazonaws.com/travis-php-archives/binaries/ubuntu/14.04/x86_64/php-5.4.tar.bz2
Failed to connect to s3.amazonaws.com port 443: Connection timed out
2)
$ composer config -g github-oauth.github.com "$GITHUB_TOKEN"
$ composer self-update
[UnexpectedValueException]
Your github oauth token for github.com contains invalid characters: ""

For example, see https://github.com/voskobovich/yii2-linker-behavior/pull/20

**Comment by voskobovich** [comment]
Fixed! Thank you 👍
