### ISSUE TITLE
Illegal string offset 'updater' LinkerBehavior:122

### ISSUE THREAD

**Issue by Enkey** [voskobovich/yii2-linker-behavior#4]
Доброго времени суток. Столкнулся с такой ошибкой `Illegal string offset 'updater'` при сохранении модели со следующим поведением: 
```php
public function behaviors()
{
    return [
        [
            'class' => \voskobovich\linker\LinkerBehavior::className(),
            'relations' => [
                'authors_ids' => 'authors',
            ],
        ],
    ];
}
```

Проблема оказалось в том, что при переборе связей, считалось, что `$params` будет массивом, а я передал строку. Поэтому сделал так:

```php
foreach ($this->relations as $attributeName => $params) {
    //...
    
    // LinkerBehavior:118
    // Make array if it is string
    if(!is_array($params) && is_string($params)) {
        $params = [$params];
    }
    //...
}
```
Решение не тестировалось при всех случаях, но в моем помогло.

**Comment by voskobovich** [comment]
Спасибо! Я посмотрю в чем дело более детально.

**Comment by Enkey** [comment]
@voskobovich Прошу прощения, не заметил что уже было это #2

**Comment by voskobovich** [comment]
@Enkey Скажи пожалуйста, проблема решилась?)

**Comment by Vuishnak** [comment]
Неа. Та же проблема...

**Comment by moneyadmin** [comment]
`composer.phar require --prefer-dist voskobovich/yii2-linker-behavior "4.0.2-rc"`
Решает проблему.

**Comment by voskobovich** [comment]
@moneyadmin спасибо за уточнение.

**Comment by voskobovich** [comment]
@Vuishnak скажи, пожалуйста, а как у тебя сейчас установлено поведение?

**Comment by Vuishnak** [comment]
@voskobovich да, по сути, так же, как и в документации.
